<?php
/*
 * Do not edit this file if you are unsure.
 */
return [

    [
        'name' => 'Customers',
        'shortname' => 'customers'
    ],
    [
        'name' => 'Companies',
        'shortname' => 'companies'
    ],
    [
        'name' => 'Transactions',
        'shortname' => 'transactions'
    ],
    [
        'name' => 'Sales',
        'shortname' => 'sales'
    ],
    [
        'name' => 'Bank & Cash',
        'shortname' => 'bank_n_cash'
    ],
    [
        'name' => 'Products & Services',
        'shortname' => 'products_n_services'
    ],
    [
        'name' => 'Reports',
        'shortname' => 'reports'
    ],
    [
        'name' => 'Utilities',
        'shortname' => 'utilities'
    ],
    [
        'name' => 'Appearance',
        'shortname' => 'appearance'
    ],
    [
        'name' => 'Plugins',
        'shortname' => 'plugins'
    ],
    [
        'name' => 'Calendar',
        'shortname' => 'calendar'
    ],
    [
        'name' => 'Leads',
        'shortname' => 'leads'
    ],
    [
        'name' => 'Tasks',
        'shortname' => 'tasks'
    ],
    [
        'name' => 'Contracts',
        'shortname' => 'contracts'
    ],
    [
        'name' => 'Orders',
        'shortname' => 'orders'
    ],
    [
        'name' => 'Settings',
        'shortname' => 'settings'
    ],
    [
        'name' => 'Documents',
        'shortname' => 'documents'
    ],
    [
        'name' => 'Purchase',
        'shortname' => 'purchase'
    ],
    [
        'name' => 'Suppliers',
        'shortname' => 'suppliers'
    ],
    [
        'name' => 'SMS',
        'shortname' => 'sms'
    ],
    [
        'name' => 'Support',
        'shortname' => 'support'
    ],
    [
        'name' => 'Knowledgebase',
        'shortname' => 'kb'
    ],
    [
        'name' => 'Password Manager',
        'shortname' => 'password_manager'
    ],
    [
        'name' => 'HRM',
        'shortname' => 'hr'
    ],

];